### ISSUE TITLE
CSS style settings

### ISSUE THREAD

**Issue by tomasell** [vaadin/vaadin-charts-flow#185]
Reading [Breaking Changes in Version 6](https://github.com/vaadin/vaadin-charts-flow/blob/master/documentation/java-api/charts-breaking-changes-in-version-6.asciidoc), you can see that `color` and `negativeColor` properties has been removed. How can set them using CSS style?
Thank for support!

**Comment by alexberazouski** [comment]
Hi, check out this demo: https://charts.demo.vaadin.com/ColorThreshold
[Here](https://www.highcharts.com/docs/chart-design-and-style/style-by-css) you can find all the css style names.

**Comment by tomasell** [comment]
@alexberazouski according with [negativeColor](https://api.highcharts.com/highstock/plotOptions.series.negativeColor) property, even if you are using style mode, you required this property. You have to set it with `true` value if you want to use `.highcharts-negative` class name.

**Comment by DiegoCardoso** [comment]
Hi, @tomasell. 

Thanks for pointing that out. We will work on a fix to enable `negativeColor` for series.
