### ISSUE TITLE
Missing GradientColor

### ISSUE THREAD

**Issue by whiteancient** [vaadin/vaadin-charts-flow#226]
The version 4 Chart had the nice class GradientColor, and the interface Color still mentions it. But it seems gone. Please put it back, it gives such nice charts.

**Comment by johannesh2** [comment]
Thanks for the report. Unfortunately does not fit into 6.1 any more. I'll add this to the 6.2 feature list.

**Comment by alvarezguille** [comment]
This issue will be fixed as part of #334

**Comment by alvarezguille** [comment]
Fixed in #334 included in Vaadin 17
