### ISSUE TITLE
Bubble Chart match custom Categories wrongly

### ISSUE THREAD

**Issue by gianluca-valentini** [vaadin/vaadin-charts-flow#229]
Hi,
I'm using the bubble chart of `com.vaadin.flow.component.charts.Chart` and an XAxis where I need to set custom Categories (the date time as String). 
Each bubble must be connected to its day on the x axis.

I used:

```
Chart actualChart = new Chart(ChartType.BUBBLE);
		Configuration conf = actualChart.getConfiguration();
		conf.setTitle((String) null);

		conf.getxAxis().setTitle("Days");
		conf.getyAxis().setTitle("Y Axis");

		conf.getxAxis().setMin(0);
		conf.getyAxis().setMin(0);
		
		conf.getxAxis().setCategories(new String[] {"2018/07/18", "2018/07/17", "2018/07/16", "2018/07/15"});

DataSeries dataSeries = new DataSeries((String) null);

		for (int i = 0; i < 4; i++) {

			DataSeriesItem3d item = new DataSeriesItem3d(8d + i, 4d + i, 7);
			item.setColorIndex(i);

			dataSeries.add(item);
		}

		PlotOptionsBubble opts = new PlotOptionsBubble();
		opts.setMaxSize("12");
		opts.setMinSize("7");

		conf.setPlotOptions(opts);

		conf.addSeries(dataSeries);
```

but the result is not correct.

![image](https://user-images.githubusercontent.com/3224592/43422532-45f95070-944a-11e8-9031-3a2530419af5.png)

**Comment by DiegoCardoso** [comment]
Hi, @gianluca-valentini 

I would say that what is making them show in different places is this line
```java
DataSeriesItem3d item = new DataSeriesItem3d(8d + i, 4d + i, 7);
```

Where you are setting the `x` value for each item as `8d + i`, so that's why the points are being displayed starting from the 8th position on the categories axis.

**Comment by gianluca-valentini** [comment]
Hi @DiegoCardoso 
thanks a lot. I believed that the categories followed the points

**Comment by gianluca-valentini** [comment]
Hi @DiegoCardoso 
I created the bubble chart using your suggestion.
I set as the X as the Y categories.

> conf.getxAxis().setCategories(new String[] { "2018/07/18", "2018/07/17", "2018/07/16", "2018/07/15" });
> 		conf.getyAxis().setCategories(new String[] { "2018/07/10", "2018/07/11", "2018/07/12", "2018/07/13" });

Do you know if there is a way to show categories values on bubble tooltip?
Currently I was able to show only the value of x using `point.category`, but I can not find a way to display the y

Thanks
Gianluca
