### ISSUE TITLE
Classname on DataSeriesItem is only added when id is set

### ISSUE THREAD

**Issue by LT-AMC** [vaadin/vaadin-charts-flow#235]
If I try to add a classname like this
```java
DataSeriesItem item = new DataSeriesItem();
item.setClassName("myClassName");
```
and take look in the browser, the item does not have "myClassName" added to it.
However, adding an id to the item like this
```java
DataSeriesItem item = new DataSeriesItem();
item.setClassName("myClassName");
item.setId("itemId");
```
the item does have both the id and the classname added to it.

**Comment by DiegoCardoso** [comment]
Hi, @LT-AMC 

Thanks for your report.

Could you provided more context about your issue? Maybe with one working example, so we could track the issue better.

**Comment by LT-AMC** [comment]
I tested it again with version 6.1.0. The bug seems to be gone now

**Comment by DiegoCardoso** [comment]
Thanks for your feedback!
