### ISSUE TITLE
Missing lineWidth accessors from PlotOptionsLine

### ISSUE THREAD

**Issue by ParthVishvajit** [vaadin/vaadin-charts-flow#248]
To set the "lineWidth" Property for the line within Line Chart, Highcharts allow us to set lineWidth property to control the line width, including making it invisible by setting lineWidth 0.
I can not find the corresponding accessor in PlotLineOptions in Vaadin Chart 6.2.0.alpha3, [here](https://vaadin.com/api/com.vaadin/vaadin-charts-flow/6.2.0.alpha3/com/vaadin/flow/component/charts/model/PlotOptionsLine.html).

The property can be found on Highcharts JS API Reference, 
[here](https://api.highcharts.com/highcharts/plotOptions.line.lineWidth).

**Comment by DiegoCardoso** [comment]
Hi, @ParthVishvajit 

Vaadin Charts from version 6.0 uses Highcharts in styled mode, which means that some of the configurations regarding styles are made via CSS. 

You can see [this example](https://charts.demo.vaadin.com/CompareMultipleSeries) of how to define a CSS module that will be applied for your chart (click on the STYLE tab).

In this case, you would style the elements with class `.highcharts-graph`, as you can see in this [Highcharts API page](https://api.highcharts.com/highcharts/plotOptions.series.lineWidth). 

So, to sumarize, it would be something like this:

##### (my-chart-theme.html)
```HTML 
<dom-module id="MyChartTheme" theme-for="vaadin-chart">
  <template>
    <style include="vaadin-chart-default-theme">
      :host(.myCssClass) .highcharts-line-series .highcharts-graph {
        stroke-width: 5;
      }
    </style>
  </template>
</dom-module>
```

More information about CSS styling can be [found here](https://vaadin.com/docs/v11/charts/java-api/css-styling.html).

**Comment by ParthVishvajit** [comment]
Thanks @DiegoCardoso 
I was not aware with class ' .highcharts-graph '. It made my code working.
It is a little bit confusing as [this](https://www.highcharts.com/docs/chart-design-and-style/style-by-css) doc says to use browser's dev tools to find out applied CSS style rules, but when I select the charts element (point of line in line chart), there was no ' .highcharts-graph ' class shown in browser's CSS rule inspector.

But your answer helped me a lot.
Thank you again.

And as per you say, It seems like the accessors are not missing and they are not there as per the plan, hence I am closing this issue.

**Comment by DiegoCardoso** [comment]
Glad to know it helped.

> It is a little bit confusing as this doc says to use browser's dev tools to find out applied CSS style rules (...)

Indeed it can be a little tricky to find the right spot because the elements on top (like points) will hide the ones on bottom (like the line) from the mouse selection.
