### ISSUE TITLE
Generated setShadow(..) method should be removed 

### ISSUE THREAD

**Issue by TatuLund** [vaadin/vaadin-charts-flow#256]
HighCharts does not support shadow when used in Styled mode as used in Vaadin Charts 6. This can be tested here: http://jsfiddle.net/alvarezg/dx3atnmp/

In addition to pie charts, I tested line and bar, and seems not to work generally.

We have generated setShadow(..) method in Vaadin Charts 6, which is hence missleading and does nothing. It should be removed.

**Comment by alvarezguille** [comment]
CSS Styled mode defaults to false in new charts version and this API will work as expected with Charts 9.
