### ISSUE TITLE
MultipleAxes: On legend click, axis title does not disappear

### ISSUE THREAD

**Issue by gianluca-valentini** [vaadin/vaadin-charts-flow#259]
I'm using Vaadin 11.
In a chart that use multiple axes, clicking on the legend the axis title does not disappear
Look https://charts.demo.vaadin.com/MultipleAxes

There is the same problem if, using the same chart, we add a drilldown.
Setting the yAxis, the other one disappear while the title is always present

**Comment by alvarezguille** [comment]
Hi @gianluca-valentini,

This is the behavior of the underlying charting library https://github.com/highcharts/highcharts/issues/8249 for backwards compatibility purposes.

I updated the demo in #260 to use `axis.setShowEmpty(false);` which will hide the axis when no data is available.
