### ISSUE TITLE
Problem with charts inside HorizontalLayout

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-charts-flow#269]
Tested on Vaadin 10.0.10 and vaadin-charts-flow 6.0.2, but probably happens in later versions
If I put two or more charts inside an HorizontalLayout (probably the same happens with other FlexComponents), and start resizing the viewport, then charts start to be drawn outside the layouts. It's easy to see in an animated gif:
![chartsizingproblem](https://user-images.githubusercontent.com/28312758/52806679-60c89180-3068-11e9-803b-ba18c030ae0f.gif)
This is the code that generated that:

```
package org.vaadin.test;

import com.vaadin.flow.component.charts.Chart;
import com.vaadin.flow.component.charts.model.AxisType;
import com.vaadin.flow.component.charts.model.ChartType;
import com.vaadin.flow.component.charts.model.Configuration;
import com.vaadin.flow.component.charts.model.DataSeries;
import com.vaadin.flow.component.charts.model.DataSeriesItem;
import com.vaadin.flow.component.charts.model.ListSeries;
import com.vaadin.flow.component.charts.model.PlotBand;
import com.vaadin.flow.component.charts.model.XAxis;
import com.vaadin.flow.component.charts.model.YAxis;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.router.Route;

@SuppressWarnings("serial")
@Route("problem")
public class ChartProblemView extends HorizontalLayout {

	public ChartProblemView() {
		setSizeFull();

		Chart approvalChart = new Chart(ChartType.SOLIDGAUGE);
		Configuration conf = approvalChart.getConfiguration();
		conf.setTitle("Test");
		YAxis yaxis = new YAxis();
		yaxis.setTitle("Test");
		yaxis.setMin(0);
		yaxis.setMax(100);
		yaxis.setVisible(false);
		ListSeries series = new ListSeries(77);
		conf.addSeries(series);
		PlotBand approved = new PlotBand(0, 77);
		PlotBand notapproved = new PlotBand(77, 100);
		yaxis.setPlotBands(approved, notapproved);
		conf.addyAxis(yaxis);

		approvalChart.setWidth("100%");
		add(approvalChart);

		Chart hoursSavedChart = new Chart(ChartType.COLUMN);
		Configuration hoursConfig = hoursSavedChart.getConfiguration();
		DataSeries hoursSavedSeries = new DataSeries();
		hoursSavedSeries.add(new DataSeriesItem("Jan", 10));
		hoursSavedSeries.add(new DataSeriesItem("Feb", 20));
		hoursSavedSeries.add(new DataSeriesItem("Mar", 30));
		hoursSavedSeries.add(new DataSeriesItem("Apr", 40));
		hoursConfig.addSeries(hoursSavedSeries);
		XAxis xaxis1 = new XAxis();
		xaxis1.setType(AxisType.CATEGORY);
		hoursConfig.addxAxis(xaxis1);

		hoursSavedChart.setWidth("100%");
		add(hoursSavedChart);
	}

}

```

At first I thought it could be related to [this issue](https://github.com/vaadin/vaadin-charts/issues/369), but I upgraded to the latest version and it's still happening. One important thing to mention is that I only was able to reproduce it by placing at least two charts inside the Layout, instead of one.

**Comment by DiegoCardoso** [comment]
We have an open PR for `vaadin-chart` that will fix this behavior, and if you take a look to it (https://github.com/vaadin/vaadin-charts/pull/434), you will noticed that it can fixed by adding `overflow: hidden` to the `host` element. 

It may take a bit of time to merge and release it, as I found another unrelated issue with latest Firefox that are breaking the tests.

Meanwhile, you can workaround this issue by applying `overflow: hidden` to `vaadin-chart`, that way Highcharts won't prevent it from shrinking on window resize and will adjust itself to the new available area.

**Comment by DiegoCardoso** [comment]
The same workaround can be done from a `Chart` instance by calling `chart.getElement().getStyle().set("overflow", "hidden")`, though you would need to do that to every element.
