### ISSUE TITLE
DataSeriesItem for Pie with Z value

### ISSUE THREAD

**Issue by releasedin** [vaadin/vaadin-charts-flow#273]
I try to reproduce this example from highcharts demo with vaadin-charts
https://www.highcharts.com/demo/variable-radius-pie

In this case, I can't set a value for Z property (which indicate the height of item) of DataSeriesItem,
I tried to extend this object, but was unsuccessful.

Can someone help me to reproduce this kind of Pie using the flow tools?

**Comment by alvarezguille** [comment]
At the moment there is no support for variable pie in vaadin charts, it requires a new chart type and some extra module imports that are not included at the moment
You can follow https://github.com/vaadin/vaadin-charts-flow/issues/211 to get updates about the new chart type
