### ISSUE TITLE
Update charts theming docs for V14

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-charts-flow#299]
[Theming docs](https://vaadin.com/docs/v14/charts/java-api/css-styling.html) are still showing the P2 way of theming.

- [ ] Migrate to use css and CSSImport
- [ ] Make sure that branch config for vaadin-docs is correct
- [ ] Bonus points for updating demos that are using a custom theme

**Comment by DiegoCardoso** [comment]
PRs for vaadin-docs done:
- V10: https://github.com/vaadin/vaadin-docs/pull/177
- V11: https://github.com/vaadin/vaadin-docs/pull/178
- V12: https://github.com/vaadin/vaadin-docs/pull/179
- V13: https://github.com/vaadin/vaadin-docs/pull/180
- V14: https://github.com/vaadin/vaadin-docs/pull/181
