### ISSUE TITLE
Add Chart#setDrilldownCallback(DrilldownCallbackHandler) back

### ISSUE THREAD

**Issue by TatuLund** [vaadin/vaadin-charts-flow#322]
In Vaadin 8 version of the Charts there was setDrilldownCallback which could be used to produce data set for the drill down. The main use case is to produce lazy data loading for drill downs.

**Comment by TatuLund** [comment]
Related to https://github.com/vaadin/vaadin-charts-flow/issues/321

**Comment by rolfsmeds** [comment]
This was untagged as BugFixPriority since it's a feature request rather than a bug.

**Comment by TatuLund** [comment]
This is however a clear regression, since the facilities to implement lazy loading drilldowns are currently broken, it was possible to do those with Vaadin 8.

**Comment by gianluca-valentini** [comment]
I have this problem too.
in one shot loading process, the page need a lot of time to be presented. For this reason I need to be able to load drilled items only when drilldown event is executed.
Is there a roadmap for this issue?

**Comment by alvarezguille** [comment]
We just started a new Charts version, updating to latest Highcharts and also bringing back some API that was available in Charts for FW8 like SVGGenerator and Java API for styling. 
I think this issue should be included in the same milestone https://github.com/vaadin/vaadin-charts-flow/milestone/10, I'll confirm before adding it (sorry I accidentally added and removed it before confirming).

**Comment by gianluca-valentini** [comment]
@alvarezguille thanx a lot
Do you have an idea about when it could be released?

**Comment by rolfsmeds** [comment]
The Charts upgrade is scheduled for V17 (Sep 2020), and will most probably be backported to the 14.x series shortly thereafter. You can see the current roadmap here: https://vaadin.com/roadmap (scroll down to "Upcoming releases").

**Comment by gianluca-valentini** [comment]
@rolfsmeds thanks a lot

**Comment by gianluca-valentini** [comment]
I will add a reminder on my personal calendar :)
