### ISSUE TITLE
Title tag is always added to the chart

### ISSUE THREAD

**Issue by tepi** [vaadin/vaadin-charts-flow#325]
Two very related issues here:

1. If you don't set any title for a chart, it will still have a <title> tag with the text "Chart", which is rendered as a tooltip in the browser. I expect there not to be a "Chart" tooltip by default.

2. If you do set a title for a chart, it is also put into the <title> tag and rendered as tooltip. I expect there to be a way to separately set the always-visible chart title and the tooltip.

**Comment by alvarezguille** [comment]
Duplicate of #270 
The title comes from accessibility features. It can be disabled with `chart.getConfiguration().setAccessibility(new Accessibility(false))`
