### ISSUE TITLE
Scatter chart: don't show elements if more than 1000

### ISSUE THREAD

**Issue by gianluca-valentini** [vaadin/vaadin-charts-flow#330]
Hi, I'm using Vaadin **14.1.18** and SCATTER chart. I have a problem when the point list si big, in my scenario the number is 1904. No point is visible. 
All of that points are inserted in the same DataSeries. 
If I reduce the point number at, 1000 for example, the points are visible.

It seems to be a limit as with 1000 points I can see the chart, with 1001 no points are visible

Looking [HighChart example](https://www.highcharts.com/demo/scatter-boost), I can see scatter with a loto of points. So maybe sometihng is missing in the realted Vaadin Chart?

**Comment by alvarezguille** [comment]
This is related to optimization done by the charting library.
You can disable this optimization by doing [setTurboThreshold(0)](https://vaadin.com/api/platform/14.1.23/com/vaadin/flow/component/charts/model/PlotOptionsScatter.html#setTurboThreshold-java.lang.Number-)
