### ISSUE TITLE
Unmapped Axis properties: lineColor and label.styles

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/vaadin-charts-flow#346]
The following properties are unmapped
- [xAxis.labels.style](https://api.highcharts.com/highcharts/xAxis.labels.style)
- [xAxis.lineColor](https://api.highcharts.com/highcharts/xAxis.lineColor)

See Highcharts example: https://jsfiddle.net/Lmkw31br/

**Comment by alvarezguille** [comment]
The mentioned API does not work in CSS Styled mode that vaadin-charts-flow currently uses.
> xAxis.labels.style
In styled mode, the labels are styled with the .highcharts-axis-labels class.

> xAxis.lineColor
In styled mode, the line stroke is given in the .highcharts-axis-line or .highcharts-xaxis-line class.

Linked documentation mentions which css classes can be used for theming.

Java API for styling will be added as part of #334 in next charts version
