### ISSUE TITLE
Charts 6 -> 9 migration: black background, chart not useful

### ISSUE THREAD

**Issue by werwolfberlin** [vaadin/vaadin-charts-flow#384]
Try to migrate https://demo.vaadin.com/charts4/#ColumnLineAndPie

most properties are easy to migrate. The result is a more or less black rectangle with no chart visible:

![image](https://user-images.githubusercontent.com/19834316/87420792-2ef98880-c5d6-11ea-8550-6e400334eb11.png)

**Comment by alvarezguille** [comment]
The black chart is a symptom of having styledMode enabled without loading chart default theme. When using java API styled mode is disabled by default and this should not happen, but in some cases it wasn't serialized properly.
This will be fixed in #386 .
