### ISSUE TITLE
Bullet Chart yAxis plot band fill color is overridden by CSS in non-styled mode

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-charts-flow#396]
My Bullet Chart is not in styled mode, but still plot band fill colors are coming from CSS.

![image](https://user-images.githubusercontent.com/1398470/89733059-9aab0600-da5b-11ea-95d2-f769a6ec6c4c.png)

**Comment by johannesh2** [comment]
I had created the project with start.vaadin.com, which includes chart theme in global-styles.js. I was not expecting to see CSS classes in a Chart that is not created in styled mode.

**Comment by alvarezguille** [comment]
When not using styled mode charts-default-theme shouldn't be imported. It's a limitation of HC, css clases are available when not in styled mode, styled mode prevents the default values used in attributes in case they are not overridden with CSS. 
Also related to #371 
Documentation could be more explicit about it and custom theme should be removed from starter wizard.

**Comment by johannesh2** [comment]
Did I understand correctly that if I have Charts code from V10+ and I want to start using Java API for styling, I can't have the existing charts using CSS styling i.e. can the same app have two kinds of charts: CSS styled and Java API styled?

**Comment by DiegoCardoso** [comment]
Yes. Only one type of styling can be used within a project, since once the CSS theme is loaded, there's no guarantee that styles applied by the Java API will work, because of the order of precedence in CSS.

The documentation regarding this behavior was added by #402
