### ISSUE TITLE
Change Java package to follow the Flow naming convention

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-charts-flow#78]
All other Flow components uses `com.vaadin.flow.component.textfield` style package names while Charts still uses `com.vaadin.addon.charts`. It should be changed to match the "standard", i.e. `com.vaadin.flow.component.charts`

**Comment by johannesh2** [comment]
Fixed in https://github.com/vaadin/vaadin-charts-flow/commit/dea4d0c29527982000b5f8db3cd4e0a8bed83c5a
