### ISSUE TITLE
Unable to set chart size

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-charts-flow#94]
If you do
```
Chart lineChart = new Chart(ChartType.LINE);
verticalLayout.add(lineChart);
```

You end up with a 0x0 size chart.

If you do
```
lineChart.getElement().getStyle().set("height", "100px");
```
you end up with a 100px high chart which will be partly covered by the next element in the vertical layout because of https://github.com/vaadin/vaadin-charts/issues/245

If you do
```
lineChart.setHeight("100px");
```
like with most other components, you get a compile error because there is no `setHeight`.

How are you supposed to use a chart if you can't size it?

**Comment by johannesh2** [comment]
Thank you for the report. Very inconvenient case indeed. If I'm not mistaken in 6.0.0.alpha11 and older you should use something else than VerticalLayout. Fix for VerticalLayout (and other flex based stuff) is coming in a future alpha.
